### ISSUE TITLE
Status 401

### ISSUE THREAD

**Issue by bigfun0815** [sven5/Lexoffice#1]
Hallo,
ich bekomme bei der Ausführung des Connectors immer die Fehlermeldung 401 "message": "Unauthorized"
Den API_Schlüssel habe ich unter Verbindungen in Flow eingetragen.
Was könnte der Fehler sein.
Vielen Dank!
Thomas

**Comment by sven5** [comment]
Hallo @bigfun0815 
Du musst den Schlüssel in diesem Format angeben: `Bearer xiwFs2anX1ljIYm0ZUXBePNMFBNwjdGp`

**Comment by bigfun0815** [comment]
Besten Dank!
Jetzt klappt alles.
